# Build stage
FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod ./
# COPY go.sum ./
# RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /server ./cmd/server/main.go

# Production runtime stage
FROM alpine:3.20

WORKDIR /app
COPY --from=builder /server /app/server

EXPOSE 8080
CMD ["/app/server"]
